// src/lib/components/InputImage.svelte
<script lang="ts">
	import { isBlob } from '$lib/util';
	import feather from 'feather-icons';
	import Button from '$lib/components/Button.svelte';

	const props = $props();
	const blobURL = isBlob(props.blob) && URL.createObjectURL(props.blob);
	const imageURL = blobURL || props.src;
	let imageFileState = $state(imageURL);

	const getImage = (image: any) => {
		if (typeof image === 'object') {
			const blob = new Blob([image], { type: 'image/png' });
			return URL.createObjectURL(blob);
		}
		return image;
	};
</script>

<div class="inputImage">
	{#if imageFileState}
		<img id="image" src={getImage(imageFileState)} alt="" />
		<Button
			class="removeImage"
			variant="outline"
			onclick={() => {
				const imageAreaEl = document.getElementById('image');
				imageFileState = null;
				props.onchange(null, null);
			}}
		>
			Remove Image
		</Button>
	{/if}
	{#if !imageFileState}
		<Button
			id="addImage"
			variant="outline"
			onclick={() => document?.getElementById('input').click()}
		>
			Add Image
		</Button>
	{/if}

	<input
		id="input"
		type="file"
		accept="image/*;capture=camera"
		onchange={(event) => {
			const imageAreaEl = document.getElementById('image');
			const file = event.target.files[0];
			const blob = new Blob([file], { type: 'image/png' });
			imageFileState = file;
			props.onchange(file, blob);
		}}
	/>
</div>

<style>
	input {
		display: none;
	}
	.inputImage :global(#addImage) {
		height: 100%;
		align-items: center;
		justify-self: center;
		width: 100%;
	}
	.addImage {
		display: flex;
		align-items: center;
		justify-content: center;
	}
	#image {
		aspect-ratio: 1/1;
		height: 33.333vh;
		object-fit: contain;
		display: flex;
		align-items: center;
		justify-self: center;
	}
	.inputImage {
		align-items: center;
		display: flex;
		height: 33.333vh;
		justify-content: center;
		padding: 0 16px;
		position: relative;
		width: 100%;
	}

	.inputImage :global(.removeImage) {
		position: absolute;
		bottom: 0;
	}
	.inputImage :global(.removeImage span) {
		background: white;
		padding: 4px 16px;
		border-radius: 8px;
	}
	.removeImage {
		position: absolute;
		bottom: 0;
	}
</style>

// app/components/InputImage/index.tsx
import { useEffect, useRef, useState } from "react";
import { Image } from "react-feather";
import style from "./style.module.css";
import Button from "../Button";
import Bar from "../Bar";

const getImage = (image: any) => {
  if (typeof image === "object") {
    const blob = new Blob([image], { type: "image/jpeg" });
    return URL.createObjectURL(blob);
  }
  return `${process.env.NEXT_PUBLIC_STORJ_PUBLIC_URL}/${image}?wrap=0`;
};

interface InputImageProps {
  className?: string;
  onChange?: (file: File | string | null) => void;
  value?: File | string | null;
}

const InputImage = ({
  className,
  onChange = () => {},
  value = null,
}: InputImageProps) => {
  const [imageFileState, setImageFileState] = useState<File | string | null>(
    value
  );
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    onChange(imageFileState);
  }, [imageFileState]);

  return (
    <div className={[style.inputImage, className].join(" ")}>
      {imageFileState && (
        <img className={style.img} src={getImage(imageFileState)} alt="" />
      )}
      {imageFileState && (
        <Bar className={style.bar}>
          <Button
            className={style.buttonRemoveImage}
            onClick={() => {
              setImageFileState(null);
            }}
            variant="fill"
          >
            Remove Image
          </Button>
        </Bar>
      )}
      {!imageFileState && (
        <Button
          className={style.buttonAddImage}
          onClick={() => inputRef.current?.click()}
        >
          <Image color="#222" />
        </Button>
      )}
      <input
        className={style.input}
        id="input"
        type="file"
        accept="image/*;capture=camera"
        onChange={async (event) => {
          const file = event.target.files?.[0];
          if (file) {
            try {
              setImageFileState(file);
            } catch (error) {
              console.error(error);
            }
          }
        }}
        ref={inputRef}
      />
    </div>
  );
};

export default InputImage;
